### ISSUE TITLE
Placeholder {player} issue

### ISSUE THREAD

**Issue by Bodlikcz** [andrei1058/SteveSus#7]
Placeholder {player} at action bar in-game sometimes doesn't show your nick instead of your color.

gm-action-bar-in-game: '&fTva barva: {player} &7| &fMistnost: {room}'
https://i.imgur.com/Bg7s8Vi.png

**Comment by andrei1058** [comment]
is the player a ghost? also provide plugin list

**Comment by Bodlikcz** [comment]
I fixed it.
